### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by faca5** [denistorresan/bybit-php-api#7]
Hello.

I got error:
`[PHP Fatal error:  Uncaught ByBit\SDK\Exceptions\HttpException: invalid request, please check your server timestamp or recv_window param. req_timestamp[1753891848000],server_timestamp[1753891839047],recv_window[5000] in ...\vendor\goodmagma\bybit-php-api\src\ApiRequest.php:150](url)`

How to synchronize the time?
`$bybitApi->getBybitServerTime();`

Thank you!

**Comment by denistorresan** [comment]
Hello @faca5 ,
the error means that the time settings on your server is not up to date.
Looking the error seems that your server is in the future compared to bybit server.

req_timestamp[1753891848000] > server_timestamp[1753891839047]

try syncronize your server time using a time server service.

let me know

**Comment by faca5** [comment]
Hello.

Time has been already synchronized with local time zone using Windows Time Server.

Binance PHP function for that:
`$api->useServerTime();
`

```
    /**
     * useServerTime adds the 'useServerTime'=>true to the API request to avoid time errors
     *
     * @link https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-endpoints
     *
     * $api->useServerTime();
     *
     * @return null
     * @throws \Exception
     */
    public function useServerTime(array $params = [])
    {
        $request = $this->apiRequest("v3/time", "GET", $params);
        if (isset($request['serverTime'])) {
            $this->info['timeOffset'] = $request['serverTime'] - (microtime(true) * 1000);
        }
    }
```

Source: https://github.com/ccxt/php-binance-api/blob/master/php-binance-api.php

**Comment by denistorresan** [comment]
would you like to make changes and send me a PR?

**Comment by faca5** [comment]
Hello

I tried but it doesn't work.

File:
src\ApiRequest.php

Variable $timestamp in function call() should be overwrite or synchronized with server time using getBybitServerTime(). This should fix the problem with time zone. It should take few minutes for you to integrate that solution.

```
        //authorization?
        if( !empty($this->key) && !empty($this->secret) ){
            **$timestamp = time() * 1000;**

            $encoded_params = '';
            if( $method == self::METHOD_GET ){
                $encoded_params = $query_string;
            }
            else{
                $encoded_params = empty($params) ? '' : json_encode($params, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
            }

            $signature_params = **$timestamp** . $this->key . self::BAPI_RECV_WINDOW . $encoded_params;
            $signature = hash_hmac('sha256', $signature_params, $this->secret);

            $options['headers']['X-BAPI-API-KEY'] = $this->key;
            $options['headers']['X-BAPI-SIGN'] = $signature;
            $options['headers']['X-BAPI-SIGN-TYPE'] = self::BAPI_SIGN_TYPE;
            **$options['headers']['X-BAPI-TIMESTAMP'] = $timestamp;**
            $options['headers']['X-BAPI-RECV-WINDOW'] = self::BAPI_RECV_WINDOW;
```

**Comment by tigger-47** [comment]
I have the same problem, unfortunately I can't solve it myself. The machine's time is synchronized daily and other exchange apis work fine. But on bybit the error still occurs sporadically. Is there a way to at least specify a larger recv_window? The parameter doesn't appear in your examples, so I don't know how to pass it. Please help! 

`invalid request, please check your server timestamp or recv_window param. req_timestamp[1754716854000],server_timestamp[1754716859213],recv_window[5000]`

I had a difference of 5213 ms for this query, so the definition of recv_window 7000 would have been sufficient (although that is probably not a solid solution, of course).

**Comment by denistorresan** [comment]
hello, actually recv is statically set at 5000, I will add a configuration to set a different recv in order to solve that problems.

thank you
